#!/usr/bin/env ruby

# If we're loading from source instead of a gem, rubygems
# isn't setting load paths for us, so we need to set it ourselves
self_load_path = File.expand_path('../lib', File.dirname(__FILE__))
$LOAD_PATH << self_load_path unless $LOAD_PATH.include? self_load_path

require 'marc_to_argot'

result = MarcToArgot::CommandLine.start(ARGV)

# non-zero exit status on process telling us there's problems.
exit 1 unless result
